# Generated by Django 4.0.6 on 2022-08-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('1', 'BMW'), ('2', 'TOYOTA'), ('3', 'TATA'), ('4', 'NISAN'), ('5', 'LAR')], default='some_y', max_length=24)),
            ],
        ),
    ]
